### ISSUE TITLE
Config the screen size break point

### ISSUE THREAD

**Issue by bigmadkev** [hbstack/header#258]
The theme is designed to collapse the menus when the width less than 1400px, and expand when the width is great than that point.

It would be great to have a way to configure this.

**Comment by razonyang** [comment]
Done, please upgrade the related header modules and tweak the `header.breakpoint` parameter (default to `lg`).

Read more on http://localhost:13131/en/modules/header/overview/.

```sh
hugo mod get -u ./...
```

Or upgrade specified modules.

```sh
hugo mod get -u \
  github.com/hbstack/header/modules/banner \
  github.com/hbstack/header/modules/theme-toggle \
  github.com/hbstack/header/modules/search \
  github.com/hbstack/header/modules/language-picker \
  github.com/hbstack/header/modules/socials
```
