### ISSUE TITLE
header text indistinguishable from background video when first displayed

### ISSUE THREAD

**Issue by pleasantone** [hbstack/header#518]
Not sure if this is the same issue as #255 , but if you look at <gtj.netlify.app> when the header is first put up, the header background is transparent, and the text may get lost because it doesn't show up against the video background (see active page Home in header).

As soon as you start to scroll, the header background changes to the theme color background. Seems like this behavior was intentional, but then we might consider doing some vignetting around the header text?

**Comment by razonyang** [comment]
There is a `color` parameter on banner, which may not be documented yet.

```yaml
---
header:
  banner:
    color: '#DD7815'
---
```

**Comment by pleasantone** [comment]
Can we make it follow the dark/light theme color?

**Comment by razonyang** [comment]
> Can we make it follow the dark/light theme color?

I didn't get it, could you please provide a reproduce steps/screenshot? Such as theme color, how to make this issue to be rendered more obviously.

The image below was captured from Chrome with _slow 3g_ network, but I didn't see a problem.

![image](https://github.com/hbstack/header/assets/17720932/02ce64d1-6d5b-4cf0-9672-046786f7bd17)

**Comment by pleasantone** [comment]
The color parameter affects the text of the banner, and the header, until you scroll... different thing.
I'm talking about the background color of the header -- making it transparent, as it is now, is problematic for distinguishing text if the contrast between the text and the background image isn't high enough...

Current: "Home" is obscured by lack of contrast:
<img width="558" alt="Screenshot 2024-02-28 at 10 34 54 AM" src="https://github.com/hbstack/header/assets/5339793/999e2677-79e3-4128-b6f3-891a389aaad0">

Proposed: dark theme
<img width="1347" alt="Screenshot 2024-02-28 at 10 35 21 AM" src="https://github.com/hbstack/header/assets/5339793/798471b6-f556-4fbb-9c5e-1f487e0137d0">

Proposed: light theme
<img width="1354" alt="Screenshot 2024-02-28 at 10 35 09 AM" src="https://github.com/hbstack/header/assets/5339793/df053b67-f7cc-4ec7-aa04-3daeb1a3ca0e">

The proposed is exactly what you get once you begin to scroll down the page... I'm just advocating for the option to do that without the need to start scrolling.

**Comment by pleasantone** [comment]
FWIW, this is a non-issue if one changes to header/theme/pills, so low priority, but still a noted issue.

**Comment by razonyang** [comment]
I see, you mean always show the original background for header menus, it's not related to CLS, and it was by designed, which the video and image is the main concern.

Anyway it make sense to add a parameter to use the original background all the time.
