### ISSUE TITLE
click in the middle of search box, not responding,  although it works when click on the magnifying glass and /. 

### ISSUE THREAD

**Issue by johnsmithodom** [hbstack/header#57]
click in the middle of search box, not responding,  although it works when click on the magnifying glass and /. 

![image](https://user-images.githubusercontent.com/120798996/235290449-f888485e-e124-43b6-9d5a-eae17a5d3df3.png)

**Comment by razonyang** [comment]
Fixed since `github.com/hbstack/header/modules/search@v0.1.10`.
